### ISSUE TITLE
dockerhub image is not updated for 2.9

### ISSUE THREAD

**Issue by nsteinmetz** [CleverCloud/clever-tools-dockerhub#2]
Hi there,

Clever Tools image on docker hub is still 2.8 ; 2.9 is not yet available.

Could you please udpate it too ?

Thanks !

**Comment by hsablonniere** [comment]
Hey @nsteinmetz, indeed. It seems to be because of plan changes on docker hub.

**Comment by hsablonniere** [comment]
We just published the `2.9.0` and `2.9.1`. Sorry for the inconvenience :hugs:
